###

GET http://localhost:3000/student/12345


###

POST  http://localhost:3000/student
Content-Type: application/json

{
    "name": "John",
    "age": 20,
    "_id": "022222022"
}

###

PUT http://localhost:3000/student

###

DELETE http://localhost:3000/student